select * from customer limit 20;

--Q1. What is total revenue generated by male vs female customers?
Select sum(purchase_amount) as revenue, gender
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer);

--Q3. Which are the top products with the highest average review rating?
Select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amount between Standard and Express Shipping.
Select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
